### ISSUE TITLE
Use indexer interface to infer provider information during `verify-ingest`

### ISSUE THREAD

**Issue by masih** [ipni/index-provider#281]
The command `provider verify-ingest` can verify that a chain of advertisements are indeed ingested by a given indexer endpoint and their entries are discoverable via the indexer node's finder API.

This command requires publisher mulitaddr as well as provider ID that should correspond to the records on successful ingest. Forming a complete multiaddr can be combersome for clients that are not familier with its structure.

Instead of explicitly asking for the user to provide all the required information as command arguments, make the arguments optional and infer the information via the given indexer nonde's `/providers/<provider-id>` endpoint if left unspecified. This makes the tool more user friendly and reduces the number of required arguments for majority of users.

**Comment by gammazero** [comment]
This functionality is now provided in ipni-cli.
