### ISSUE TITLE
Separate announcement sender from libp2p host config

### ISSUE THREAD

**Issue by masih** [ipni/index-provider#364]
Sender of announcements are a separate construct than publishers. But the current engine implementation implicitly publishes over gossipsub [if a libp2p host is present](https://github.com/ipni/index-provider/blob/main/engine/engine.go#L229-L239).

Change the engine options such that the sender constructs are clearly separated from publisher and reflect the API exposed by go-libipni.

**Comment by gammazero** [comment]
Fixed by #422
