### ISSUE TITLE
Outdated code comment

### ISSUE THREAD

**Issue by dennis-tra** [ipni/index-provider#365]
I just saw this log message during my experiments which got me confused:

```
Latest advertisement CID was undefined - no previous advertisement
```

I saw that this is coming from here: https://github.com/ipni/index-provider/blob/83b5d33f6dbcc3ada3e4fba0864e7b931c5b84f1/engine/engine.go#L581

However, the comment + log message seem not to have been updated together with this change: 

https://github.com/ipni/index-provider/commit/07e2f7ca8b126f92890e109a4f4143442b1feede#diff-2e6c4934f63ff9b712c2c346b33036af4724adf70b0801fff9b74f71b37fcd89

Not urgent or anything; I just wanted to leave this here as I was confused about what's happening.

**Comment by gammazero** [comment]
Thank you.  Fixed in #368
